services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blockchain-price-tracker:${VERSION:-latest}
    container_name: blockchain-tracker-app
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL=${DB_SSL:-true}
      - TYPEORM_SYNC=${TYPEORM_SYNC:-false}
      - TYPEORM_MIGRATIONS_RUN=${TYPEORM_MIGRATIONS_RUN:-true}
      - DB_CONNECTION_TIMEOUT=${DB_CONNECTION_TIMEOUT:-30000}
      - DB_RETRY_ATTEMPTS=${DB_RETRY_ATTEMPTS:-5}
      - DB_RETRY_DELAY=${DB_RETRY_DELAY:-3000}
      - MORALIS_API_KEY=${MORALIS_API_KEY}
      - PORT=${PORT:-3000}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT:-3000}/health']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: blockchain-tracker-network
